[package]
name = "devbox"
version = "0.1.0"
edition = "2024"


[dependencies]
actix-web = "4.12.1"
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.49.0", features = ["full"] }
sqlx = { version = "0.8.6", default-features = false, features = [
  "runtime-tokio",
  "macros",
  "postgres",
  "uuid",
  "chrono",
  "migrate",
] }
config = "0.15.19"
uuid = { version = "1.21.0", features = ["v4"] }
chrono = "0.4.43"
[lib]
path = "src/lib.rs"

[[bin]]
name = "devbox"
path = "src/main.rs"

[dev-dependencies]
reqwest = "0.13.2"
